-- Creazione del database con le tabelle impiegato e datore

CREATE TABLE IF NOT EXISTS impiegato (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cognome TEXT NOT NULL,
    data_nascita DATE NOT NULL,
    ruolo TEXT NOT NULL,
    stipendio REAL NOT NULL,
    id_datore INTEGER,
    FOREIGN KEY (id_datore) REFERENCES datore(id)
);

CREATE TABLE IF NOT EXISTS datore (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cognome TEXT NOT NULL,
    azienda TEXT NOT NULL
);

-- Inserimento dati di esempio
INSERT INTO datore (nome, cognome, azienda) VALUES
('Mario', 'Rossi', 'Tech Corp'),
('Giulia', 'Verdi', 'Finance Inc'),
('Luca', 'Bianchi', 'Web Solutions'),
('Elisa', 'Galli', 'Marketing Hub'),
('Federico', 'Mancini', 'AI Innovations'),
('Sara', 'Moretti', 'Cloud Systems'),
('Antonio', 'Rinaldi', 'Cyber Security Ltd'),
('Martina', 'De Angelis', 'E-commerce World'),
('Davide', 'Fontana', 'Automotive Future'),
('Claudia', 'Serafini', 'Data Analytics'),
('Stefano', 'Marchesi', 'Green Energy Co'),
('Roberto', 'Ferri', 'Blockchain Enterprises'),
('Francesca', 'Gentile', 'Smart Tech'),
('Alessandro', 'Riva', 'Software Solutions'),
('Valentina', 'Sartori', 'Consulting Experts'),
('Emanuele', 'De Rosa', 'AI Startups'),
('Cristina', 'Ferrara', 'Medical Innovations'),
('Gabriele', 'Longo', 'EdTech Solutions'),
('Paola', 'D’Amico', 'Retail Future'),
('Nicola', 'Pellegrini', 'Smart Homes'),
('Andrea', 'Marchetti', 'FoodTech'),
('Silvia', 'Fabbri', 'Legal Advisors'),
('Matteo', 'Gallo', 'Real Estate Services'),
('Giorgia', 'Negri', 'Cloud Hosting'),
('Enrico', 'Lombardi', 'Manufacturing Inc'),
('Alberto', 'Benedetti', 'Data Science Co'),
('Veronica', 'Testa', 'Creative Agency'),
('Fabio', 'Ricci', 'Security Experts'),
('Serena', 'Leone', 'HR Solutions'),
('Lorenzo', 'De Santis', 'Game Development'),
('Beatrice', 'Conti', 'AI Robotics'),
('Daniele', 'Romano', 'BioTech'),
('Giovanni', 'Villa', 'Marketing Agency'),
('Marina', 'Landi', 'Luxury Goods'),
('Pietro', 'Grassi', 'Industrial Automation'),
('Simona', 'Serra', '3D Printing Solutions'),
('Tommaso', 'Caruso', 'Media Productions'),
('Flavia', 'Parisi', 'Crypto Startups'),
('Giacomo', 'Barone', 'Event Management'),
('Eleonora', 'Montanari', 'EdTech Innovations'),
('Riccardo', 'Fiore', 'Transportation Tech'),
('Giulia', 'Morelli', 'Consulting Experts'),
('Franco', 'Rizzi', 'Blockchain Labs'),
('Tiziana', 'De Luca', 'Sustainable Energy'),
('Marco', 'Colombo', 'AI Assistants'),
('Sabrina', 'Pagano', 'FinTech Solutions'),
('Luca', 'Sanna', 'Software Development'),
('Monica', 'Fontana', 'Luxury Consulting'),
('Stefano', 'Bianchi', 'Smart Agriculture');

-- Inserimento dati di esempio per impiegati
INSERT INTO impiegato (nome, cognome, data_nascita, ruolo, stipendio, id_datore) VALUES
('Luca', 'Bianchi', '1985-06-15', 'Developer', 32000, 1),
('Anna', 'Neri', '1990-09-23', 'Analyst', 28000, 2),
('Marco', 'Esposito', '1987-03-12', 'Project Manager', 45000, 3),
('Chiara', 'Romano', '1992-11-30', 'UX Designer', 31000, 4),
('Paolo', 'Ferrari', '1988-07-20', 'Data Scientist', 50000, 5),
('Elena', 'Russo', '1993-05-25', 'Cloud Engineer', 40000, 6),
('Giovanni', 'Pellegrini', '1984-04-18', 'Cyber Security Specialist', 47000, 7),
('Alessia', 'Conti', '1995-08-22', 'Marketing Specialist', 29000, 8),
('Riccardo', 'Barbieri', '1986-12-10', 'Mechanical Engineer', 42000, 9),
('Francesca', 'Martini', '1991-02-14', 'Data Analyst', 38000, 10),
('Simone', 'De Luca', '1989-10-05', 'Renewable Energy Engineer', 44000, 11),
('Sara', 'Morelli', '1994-06-18', 'Software Developer', 33000, 12),
('Matteo', 'Fabbri', '1983-09-27', 'AI Researcher', 48000, 13),
('Veronica', 'Testa', '1996-01-15', 'HR Manager', 35000, 14),
('Daniele', 'Romano', '1987-04-30', 'Legal Advisor', 37000, 15),
('Flavia', 'Parisi', '1992-07-19', 'Business Consultant', 36000, 16),
('Tommaso', 'Caruso', '1989-03-25', 'Network Administrator', 34000, 17),
('Giacomo', 'Barone', '1995-05-10', 'Systems Engineer', 41000, 18),
('Eleonora', 'Montanari', '1993-11-21', 'Accountant', 30000, 19),
('Riccardo', 'Fiore', '1986-08-14', 'Robotics Engineer', 46000, 20);
